use std::collections::BTreeSet;
use std::fs;
#[cfg(unix)]
use std::os::unix::fs as unix_fs;

use serde_json::Value;

use super::{TempRoot, json_cmd, root_str, run, temp_root};

const AGENT_RULES_BEGIN: &str = "<!-- BEGIN JIKJI ROUTING (auto-generated by `jikji prepare`; do not edit inside this block) -->";
const AGENT_RULES_END: &str = "<!-- END JIKJI ROUTING -->";

#[test]
fn clean_preserves_forged_cache_shaped_files_when_document_index_is_forged() {
    let root = prepared_root("forged-cache");
    let digest = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
    let text_cache = root.join(format!(".jikji/doc_text/sha256_{digest}.txt"));
    let doc_meta = root.join(format!(".jikji/doc_meta/sha256_{digest}.json"));
    fs::write(&text_cache, "user-authored cache-shaped text").expect("write fake cache");
    fs::write(&doc_meta, r#"{"user":true}"#).expect("write fake meta");
    fs::write(
        root.join(".jikji/document_index.jsonl"),
        format!(
            "{{\"text_cache_path\":\".jikji/doc_text/sha256_{digest}.txt\",\"doc_meta_path\":\".jikji/doc_meta/sha256_{digest}.json\"}}\n"
        ),
    )
    .expect("forge document index");

    let cleaned = json_cmd(["clean", root_str(&root).as_str(), "--json"]);

    assert_eq!(cleaned["ok"], true);
    assert!(text_cache.exists());
    assert!(doc_meta.exists());
}

#[cfg(unix)]
#[test]
fn clean_preserves_in_root_files_when_document_index_is_symlinked_outside_root() {
    let root = prepared_root("symlinked-index");
    let outside = temp_root("outside-index");
    let digest = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
    let text_cache = root.join(format!(".jikji/doc_text/sha256_{digest}.txt"));
    fs::write(&text_cache, "user cache-shaped file").expect("write fake cache");
    fs::write(
        outside.join("document_index.jsonl"),
        format!("{{\"text_cache_path\":\".jikji/doc_text/sha256_{digest}.txt\"}}\n"),
    )
    .expect("write outside index");
    fs::remove_file(root.join(".jikji/document_index.jsonl")).expect("remove generated index");
    unix_fs::symlink(
        outside.join("document_index.jsonl"),
        root.join(".jikji/document_index.jsonl"),
    )
    .expect("symlink index");

    let cleaned = json_cmd(["clean", root_str(&root).as_str(), "--json"]);

    assert_eq!(cleaned["ok"], true);
    assert!(text_cache.exists());
}

#[test]
fn clean_json_reports_malformed_manifest_as_structured_json() {
    let root = temp_root("clean-bad-manifest");
    fs::create_dir(root.join(".jikji")).expect("create sidecar");
    fs::write(root.join(".jikji/manifest.json"), "{not-json").expect("write bad manifest");

    let output = run(["clean", root_str(&root).as_str(), "--json"]);

    assert!(!output.status.success());
    let report: Value = serde_json::from_slice(&output.stdout).expect("json stdout");
    assert_eq!(report["ok"], false);
    assert_eq!(report["reason"], "malformed_manifest");
    assert!(report["error"].as_str().expect("error").contains("JSON"));
}

#[test]
fn clean_success_json_matches_python_key_set_and_agent_rule_cleanup() {
    let root = prepared_root("clean-json-key-set");
    let pure_rule = root.join("AGENTS.md");
    let mixed_rule = root.join("CLAUDE.md");
    fs::write(
        &pure_rule,
        format!("{AGENT_RULES_BEGIN}\nmanaged\n{AGENT_RULES_END}\n"),
    )
    .expect("write pure rule");
    fs::write(
        &mixed_rule,
        format!("user note\n\n{AGENT_RULES_BEGIN}\nmanaged\n{AGENT_RULES_END}\n"),
    )
    .expect("write mixed rule");

    let dry = json_cmd(["clean", root_str(&root).as_str(), "--dry-run", "--json"]);

    assert_clean_success_key_set(&dry);
    assert_path_list_contains(&dry["would_remove"], "AGENTS.md");
    assert_path_list_contains(&dry["agent_rules_edited"], "CLAUDE.md");
    assert!(pure_rule.exists());
    assert!(
        fs::read_to_string(&mixed_rule)
            .expect("read mixed dry-run")
            .contains(AGENT_RULES_BEGIN)
    );

    let cleaned = json_cmd(["clean", root_str(&root).as_str(), "--json"]);

    assert_clean_success_key_set(&cleaned);
    assert_path_list_contains(&cleaned["would_remove"], "AGENTS.md");
    assert_path_list_contains(&cleaned["removed"], "AGENTS.md");
    assert_path_list_contains(&cleaned["agent_rules_edited"], "CLAUDE.md");
    assert!(!pure_rule.exists());
    let mixed_text = fs::read_to_string(mixed_rule).expect("read mixed");
    assert_eq!(mixed_text, "user note\n");
}

#[test]
fn clean_removes_generated_dirs_after_their_generated_entries_are_removed() {
    let root = prepared_root("clean-generated-dirs");
    let user_note = root.join(".jikji/user-created-note.txt");
    fs::write(&user_note, "user").expect("write user note");

    let cleaned = json_cmd(["clean", root_str(&root).as_str(), "--json"]);

    assert_eq!(cleaned["ok"], true);
    assert!(user_note.exists());
    assert!(!root.join(".jikji/wiki").exists());
    assert!(!root.join(".jikji/doc_text").exists());
    assert!(!root.join(".jikji/doc_meta").exists());
}

#[cfg(unix)]
#[test]
fn clean_skips_symlinked_agent_rule_files() {
    let root = prepared_root("clean-agent-rule-symlink");
    let outside = temp_root("agent-rule-outside");
    let outside_rule = outside.join("AGENTS.md");
    fs::write(
        &outside_rule,
        format!("{AGENT_RULES_BEGIN}\nmanaged outside\n{AGENT_RULES_END}\n"),
    )
    .expect("write outside rule");
    fs::remove_file(root.join("AGENTS.md")).expect("remove generated rule fixture");
    unix_fs::symlink(&outside_rule, root.join("AGENTS.md")).expect("symlink rule");

    let cleaned = json_cmd(["clean", root_str(&root).as_str(), "--json"]);

    assert_clean_success_key_set(&cleaned);
    assert!(outside_rule.exists());
    assert!(
        fs::read_to_string(outside_rule)
            .expect("read outside rule")
            .contains("managed outside")
    );
}

#[test]
fn doctor_json_reports_malformed_manifest_as_structured_json() {
    let root = temp_root("doctor-bad-manifest");
    fs::create_dir(root.join(".jikji")).expect("create sidecar");
    fs::write(root.join(".jikji/manifest.json"), "{not-json").expect("write bad manifest");

    let output = run(["doctor", root_str(&root).as_str(), "--json"]);

    assert!(!output.status.success());
    let report: Value = serde_json::from_slice(&output.stdout).expect("json stdout");
    assert_eq!(report["ok"], false);
    assert!(
        report["errors"]
            .as_array()
            .expect("errors")
            .iter()
            .any(|error| error
                .as_str()
                .expect("error")
                .contains("malformed manifest"))
    );
}

fn prepared_root(label: &str) -> TempRoot {
    let root = temp_root(label);
    fs::write(root.join("source.txt"), "source").expect("write source");
    let prepared = json_cmd(["prepare", root_str(&root).as_str(), "--json"]);
    assert_eq!(prepared["files"], 1);
    root
}

fn assert_clean_success_key_set(value: &Value) {
    let keys = value
        .as_object()
        .expect("clean json object")
        .keys()
        .cloned()
        .collect::<BTreeSet<_>>();
    assert_eq!(
        keys,
        [
            "agent_rules_edited",
            "dry_run",
            "ok",
            "preserved_original_files",
            "reason",
            "removed",
            "root",
            "would_remove",
        ]
        .into_iter()
        .map(str::to_owned)
        .collect::<BTreeSet<_>>()
    );
    assert!(value.get("error").is_none());
}

fn assert_path_list_contains(value: &Value, suffix: &str) {
    assert!(
        value
            .as_array()
            .expect("path list")
            .iter()
            .any(|path| path.as_str().expect("path").ends_with(suffix)),
        "missing suffix {suffix} in {value:?}"
    );
}
