use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use serde::{Deserialize, Serialize};
use serde_json::Value;
use sha2::{Digest, Sha256};

const AGENT_RULES_BEGIN: &str = "<!-- BEGIN JIKJI ROUTING (auto-generated by `jikji prepare`; do not edit inside this block) -->";
const AGENT_RULES_END: &str = "<!-- END JIKJI ROUTING -->";
const AGENT_RULE_FILES: &[&str] = &["AGENTS.md", "CLAUDE.md", ".cursorrules"];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IndexStatus {
    Missing,
    Ready,
    StaleUsingPreviousIndex,
    ChangedUsingPreviousIndex,
}

impl IndexStatus {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Missing => "missing",
            Self::Ready => "ready",
            Self::StaleUsingPreviousIndex => "stale_using_previous_index",
            Self::ChangedUsingPreviousIndex => "changed_using_previous_index",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SearchIndexStatus {
    pub status: IndexStatus,
    pub should_prepare: bool,
}

pub fn search_index_status(root: &Path, stale_after_seconds: i64) -> SearchIndexStatus {
    let index = root.join(".jikji/search_index.sqlite");
    if !index.exists() {
        return SearchIndexStatus {
            status: IndexStatus::Missing,
            should_prepare: true,
        };
    }
    let manifest = read_manifest(root);
    if tree_changed(root, &manifest) {
        return SearchIndexStatus {
            status: IndexStatus::ChangedUsingPreviousIndex,
            should_prepare: false,
        };
    }
    if stale_after_seconds >= 0 {
        let age = generated_age_seconds(&index, &manifest);
        if age >= stale_after_seconds as u64 {
            return SearchIndexStatus {
                status: IndexStatus::StaleUsingPreviousIndex,
                should_prepare: false,
            };
        }
    }
    SearchIndexStatus {
        status: IndexStatus::Ready,
        should_prepare: false,
    }
}

fn read_manifest(root: &Path) -> Value {
    let path = root.join(".jikji/manifest.json");
    fs::read_to_string(path)
        .ok()
        .and_then(|text| serde_json::from_str(&text).ok())
        .unwrap_or(Value::Null)
}

fn tree_changed(root: &Path, manifest: &Value) -> bool {
    let stored = manifest
        .get("source_tree_signature")
        .and_then(|value| value.get("digest"))
        .and_then(Value::as_str);
    let Some(stored) = stored else {
        return false;
    };
    compute_source_tree_digest(root) != stored
}

fn compute_source_tree_digest(root: &Path) -> String {
    let mut files = Vec::new();
    collect_files(root, root, &mut files);
    files.sort();
    let mut hasher = Sha256::new();
    for path in files {
        let Ok(metadata) = fs::metadata(&path) else {
            continue;
        };
        let rel = path
            .strip_prefix(root)
            .unwrap_or(&path)
            .to_string_lossy()
            .replace(std::path::MAIN_SEPARATOR, "/");
        hasher.update(rel.as_bytes());
        hasher.update(b"\0");
        hasher.update(metadata.len().to_string().as_bytes());
        hasher.update(b"\0");
        hasher.update(mtime_ns(&metadata).to_string().as_bytes());
        hasher.update(b"\n");
    }
    format!("{:x}", hasher.finalize())
}

fn collect_files(root: &Path, current: &Path, files: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(current) else {
        return;
    };
    for entry in entries.flatten() {
        let name = entry.file_name().to_string_lossy().into_owned();
        if name == ".jikji" || name.starts_with('.') || is_sensitive(&name) {
            continue;
        }
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        let path = entry.path();
        if file_type.is_dir() {
            collect_files(root, &path, files);
        } else if file_type.is_file()
            && path.starts_with(root)
            && !is_pure_generated_agent_rule(&path, &name)
        {
            files.push(path);
        }
    }
}

fn is_pure_generated_agent_rule(path: &Path, name: &str) -> bool {
    if !AGENT_RULE_FILES.contains(&name) {
        return false;
    }
    let Ok(text) = fs::read_to_string(path) else {
        return false;
    };
    let trimmed = text.trim();
    trimmed.starts_with(AGENT_RULES_BEGIN) && trimmed.ends_with(AGENT_RULES_END)
}

fn is_sensitive(name: &str) -> bool {
    matches!(
        name,
        ".git" | ".hg" | ".svn" | "node_modules" | "__pycache__" | ".venv" | "venv"
    ) || name.ends_with(".pem")
        || name.ends_with(".key")
}

fn generated_age_seconds(index: &Path, manifest: &Value) -> u64 {
    if let Some(seconds) = manifest.get("generated_at").and_then(Value::as_u64) {
        return now_seconds().saturating_sub(seconds);
    }
    fs::metadata(index)
        .ok()
        .and_then(|metadata| metadata.modified().ok())
        .and_then(|modified| modified.duration_since(UNIX_EPOCH).ok())
        .map_or(0, |mtime| now_seconds().saturating_sub(mtime.as_secs()))
}

fn now_seconds() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |duration| duration.as_secs())
}

fn mtime_ns(metadata: &fs::Metadata) -> u128 {
    metadata
        .modified()
        .ok()
        .and_then(|modified| modified.duration_since(UNIX_EPOCH).ok())
        .map_or(0, |duration| duration.as_nanos())
}
