use std::fs;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use jikji_core::{Result, io_error};
use serde::Serialize;

pub const AGENT_RULES_BEGIN: &str = "<!-- BEGIN JIKJI ROUTING (auto-generated by `jikji prepare`; do not edit inside this block) -->";
pub const AGENT_RULES_END: &str = "<!-- END JIKJI ROUTING -->";
pub const AGENT_RULE_FILES: &[&str] = &["AGENTS.md", "CLAUDE.md", ".cursorrules"];

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct RoutingBlockChange {
    pub path: PathBuf,
    pub changed: bool,
    pub removed: bool,
}

pub fn write_routing_blocks(root: &Path) -> Result<Vec<RoutingBlockChange>> {
    let clean_root = canonical_dir(root)?;
    AGENT_RULE_FILES
        .iter()
        .map(|file_name| write_routing_block(&clean_root.join(file_name)))
        .collect()
}

pub fn remove_routing_blocks(root: &Path) -> Result<Vec<RoutingBlockChange>> {
    let clean_root = canonical_dir(root)?;
    AGENT_RULE_FILES
        .iter()
        .map(|file_name| remove_routing_block(&clean_root.join(file_name)))
        .collect()
}

pub fn write_routing_block(path: &Path) -> Result<RoutingBlockChange> {
    let existing = read_optional(path)?;
    let next = upsert_block(existing.as_deref());
    if existing.as_deref() == Some(next.as_str()) {
        return Ok(change(path, false, false));
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| io_error(parent, source))?;
    }
    fs::write(path, next).map_err(|source| io_error(path, source))?;
    Ok(change(path, true, false))
}

pub fn remove_routing_block(path: &Path) -> Result<RoutingBlockChange> {
    let Some(existing) = read_optional(path)? else {
        return Ok(change(path, false, false));
    };
    let next = strip_block(&existing);
    if next == existing {
        return Ok(change(path, false, false));
    }
    if next.trim().is_empty() {
        fs::remove_file(path).map_err(|source| io_error(path, source))?;
        return Ok(change(path, true, true));
    }
    fs::write(path, next).map_err(|source| io_error(path, source))?;
    Ok(change(path, true, false))
}

fn change(path: &Path, changed: bool, removed: bool) -> RoutingBlockChange {
    RoutingBlockChange {
        path: path.to_path_buf(),
        changed,
        removed,
    }
}

fn routing_block() -> String {
    format!(
        "{AGENT_RULES_BEGIN}\n{}\n{AGENT_RULES_END}\n",
        [
            "Jikji is installed for this root.",
            "For local file discovery, run `jikji find ROOT \"query\" --json` first.",
            "Follow `handoff_action` and `tool_call_policy`; raw crawling is fallback only after Jikji permits it.",
            "Never move, rename, delete, or reorganize user files."
        ]
        .join("\n")
    )
}

fn upsert_block(existing: Option<&str>) -> String {
    let block = routing_block();
    let Some(text) = existing else {
        return block;
    };
    let stripped = strip_block(text);
    if stripped.trim().is_empty() {
        return block;
    }
    format!("{}\n{}", stripped.trim_end(), block)
}

fn strip_block(text: &str) -> String {
    let mut out = String::new();
    let mut rest = text;
    loop {
        let Some(start) = rest.find(AGENT_RULES_BEGIN) else {
            out.push_str(rest);
            break;
        };
        out.push_str(&rest[..start]);
        let after_start = &rest[start..];
        let Some(end) = after_start.find(AGENT_RULES_END) else {
            out.push_str(after_start);
            break;
        };
        rest = &after_start[end + AGENT_RULES_END.len()..];
        if let Some(stripped) = rest.strip_prefix('\n') {
            rest = stripped;
        }
    }
    out
}

fn read_optional(path: &Path) -> Result<Option<String>> {
    match fs::read_to_string(path) {
        Ok(text) => Ok(Some(text)),
        Err(source) if source.kind() == ErrorKind::NotFound => Ok(None),
        Err(source) => Err(io_error(path, source)),
    }
}

fn canonical_dir(path: &Path) -> Result<PathBuf> {
    let clean = path
        .canonicalize()
        .map_err(|source| io_error(path, source))?;
    if clean.is_dir() {
        Ok(clean)
    } else {
        Err(io_error(
            path,
            std::io::Error::new(
                std::io::ErrorKind::InvalidInput,
                format!("path is not a directory: {}", clean.display()),
            ),
        ))
    }
}
