use std::fs;

use jikji_core::{
    JIKJI_DIR, OWNED_GENERATED_PATHS, PrepareOptions, RETIRED_GENERATED_PATHS, ROOT_AGENT_MAP,
    Result, ensure_generated_dir, io_error,
};
use jikji_search::SearchArtifactStats;
use serde_json::{Value, json};

use crate::artifact_rows::native_text_extensions;
use crate::doc_cache::{DOCUMENT_EXTENSIONS, DocumentBuild};
use crate::doc_media::MEDIA_EXTENSIONS;
use crate::file_io::{extension, unix_seconds_now, write_json};
use crate::scan::{ScanResult, rel_path};

const SEARCH_SCHEMA_VERSION: u8 = 3;
const CACHE_KEY_POLICY: &str =
    "sha256, recomputed only when size or mtime_ns changed or cache is missing";

pub(crate) fn write_static_artifacts(
    scan: &ScanResult,
    options: &PrepareOptions,
    docs: &DocumentBuild,
    search_stats: SearchArtifactStats,
) -> Result<()> {
    let index_dir = scan.root.join(JIKJI_DIR);
    let media_files = scan
        .files
        .iter()
        .filter(|path| MEDIA_EXTENSIONS.contains(&extension(path).as_str()))
        .count();
    let manifest = json!({
        "schema_version": 1,
        "search_index_schema_version": SEARCH_SCHEMA_VERSION,
        "generated_at": unix_seconds_now(),
        "root": scan.root,
        "files": scan.signature.files,
        "folders": scan.signature.folders,
        "documents": docs.rows.len(),
        "chunks": docs.chunk_rows.len(),
        "docs_parsed": docs.rows.len(),
        "docs_reused": 0,
        "docs_failed": 0,
        "parse_errors": 0,
        "deleted_since_last_index": 0,
        "mode": "agent_search",
        "non_destructive": true,
        "cache_key_policy": CACHE_KEY_POLICY,
        "owned_paths": OWNED_GENERATED_PATHS,
        "retired_cleanup_paths": RETIRED_GENERATED_PATHS,
        "parser_required_extensions": DOCUMENT_EXTENSIONS.iter().map(|ext| format!(".{ext}")).collect::<Vec<_>>(),
        "native_text_extensions": native_text_extensions(),
        "media_index": {
            "enabled": options.enable_media_index,
            "status": media_status(options.enable_media_index, media_files),
            "media_files": media_files,
            "max_mb": options.media_index_max_mb,
            "note": "image/audio/video OCR-ASR is opt-in; metadata is recorded by default"
        },
        "source_tree_signature": scan.signature,
        "search_index_bytes": search_index_bytes(&index_dir),
        "llm_wiki": ".jikji/wiki/index.md",
        "knowledge_graph": ".jikji/knowledge_graph.json",
        "graph_routes": ".jikji/graph_routes.jsonl",
        "llm_wiki_schema": ".jikji/llm_wiki_schema.md",
        "llm_wiki_sources": search_stats.rows,
        "knowledge_graph_nodes": search_stats.graph_nodes,
        "knowledge_graph_edges": search_stats.graph_edges,
    });
    write_json(index_dir.join("manifest.json"), &manifest)?;
    write_json(
        index_dir.join("corpus_profile.json"),
        &json!({"schema_version": 1}),
    )?;
    write_json(index_dir.join("intent_taxonomy.json"), &json!({}))?;
    write_json(
        index_dir.join("autorag_manifest.json"),
        &json!({"schema_version": 1}),
    )?;
    write_markdown_files(scan, &manifest)
}

fn write_markdown_files(scan: &ScanResult, manifest: &Value) -> Result<()> {
    let index_dir = scan.root.join(JIKJI_DIR);
    let map = agent_map(scan, manifest);
    fs::write(index_dir.join("agent_map.md"), &map)
        .map_err(|source| io_error(index_dir.join("agent_map.md"), source))?;
    fs::write(scan.root.join(ROOT_AGENT_MAP), &map)
        .map_err(|source| io_error(scan.root.join(ROOT_AGENT_MAP), source))?;
    fs::write(
        index_dir.join("agent_routes.md"),
        "# Jikji Agent Routes\n\nUse `.jikji/file_index.jsonl` first.\n",
    )
    .map_err(|source| io_error(index_dir.join("agent_routes.md"), source))?;
    fs::write(
        index_dir.join("agent_skill_context.md"),
        "# Jikji Agent Skill Context\n\nGenerated by `jikji prepare`.\n",
    )
    .map_err(|source| io_error(index_dir.join("agent_skill_context.md"), source))?;
    fs::write(
        index_dir.join("human_guide.md"),
        "# Jikji Human Guide\n\nOriginal files were not moved, renamed, or deleted.\n",
    )
    .map_err(|source| io_error(index_dir.join("human_guide.md"), source))?;
    ensure_generated_dir(&index_dir.join("wiki"))?;
    if !index_dir.join("wiki").join("index.md").exists() {
        fs::write(index_dir.join("wiki").join("index.md"), "# Jikji Wiki\n")
            .map_err(|source| io_error(index_dir.join("wiki").join("index.md"), source))?;
    }
    Ok(())
}

fn agent_map(scan: &ScanResult, manifest: &Value) -> String {
    let mut lines = vec![
        "# Jikji Agent Map".to_owned(),
        String::new(),
        "Original files were not moved, renamed, or deleted.".to_owned(),
        format!("- Root: {}", scan.root.display()),
        format!("- Files: {}", manifest["files"]),
        format!("- Folders: {}", manifest["folders"]),
        String::new(),
        "## Files".to_owned(),
    ];
    lines.extend(
        scan.files
            .iter()
            .map(|path| format!("- {}", rel_path(&scan.root, path))),
    );
    lines.push(String::new());
    lines.join("\n")
}

fn media_status(enabled: bool, media_files: usize) -> &'static str {
    match (enabled, media_files) {
        (true, _) => "enabled_bounded",
        (false, 0) => "no_media_files",
        (false, _) => "metadata_only_opt_in_available",
    }
}

fn search_index_bytes(index_dir: &std::path::Path) -> u64 {
    index_dir
        .join("search_index.sqlite")
        .metadata()
        .map_or(0, |metadata| metadata.len())
}
