use std::fs;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use jikji_core::{Result, io_error};

const AGENT_RULES_BEGIN: &str = "<!-- BEGIN JIKJI ROUTING (auto-generated by `jikji prepare`; do not edit inside this block) -->";
const AGENT_RULES_END: &str = "<!-- END JIKJI ROUTING -->";
const AGENT_RULE_FILES: &[&str] = &["AGENTS.md", "CLAUDE.md", ".cursorrules"];

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct AgentRuleCleanResult {
    pub(crate) edited: Vec<PathBuf>,
    pub(crate) removed: Vec<PathBuf>,
}

pub(crate) fn clean_agent_rules(root: &Path, dry_run: bool) -> Result<AgentRuleCleanResult> {
    let mut edited = Vec::new();
    let mut removed = Vec::new();
    for name in AGENT_RULE_FILES {
        let path = root.join(name);
        let metadata = match fs::symlink_metadata(&path) {
            Ok(metadata) => metadata,
            Err(source) if source.kind() == ErrorKind::NotFound => continue,
            Err(source) => return Err(io_error(&path, source)),
        };
        let file_type = metadata.file_type();
        if !file_type.is_file() || file_type.is_symlink() {
            continue;
        }
        let text = fs::read_to_string(&path).map_err(|source| io_error(&path, source))?;
        let Some(stripped) = strip_agent_rules_block(&text) else {
            continue;
        };
        if stripped.trim().is_empty() {
            removed.push(path.clone());
            if !dry_run {
                fs::remove_file(&path).map_err(|source| io_error(&path, source))?;
            }
        } else {
            edited.push(path.clone());
            if !dry_run {
                fs::write(&path, format!("{}\n", stripped.trim_end_matches('\n')))
                    .map_err(|source| io_error(&path, source))?;
            }
        }
    }
    Ok(AgentRuleCleanResult { edited, removed })
}

fn strip_agent_rules_block(text: &str) -> Option<String> {
    let mut out = String::new();
    let mut rest = text;
    let mut changed = false;
    loop {
        let Some(start) = rest.find(AGENT_RULES_BEGIN) else {
            out.push_str(rest);
            break;
        };
        out.push_str(&rest[..start]);
        let after_start = &rest[start..];
        let Some(end) = after_start.find(AGENT_RULES_END) else {
            out.push_str(after_start);
            break;
        };
        changed = true;
        rest = &after_start[end + AGENT_RULES_END.len()..];
        if let Some(stripped) = rest.strip_prefix('\n') {
            rest = stripped;
        }
    }
    changed.then_some(out)
}
