use std::fs;
use std::path::{Path, PathBuf};
use std::time::UNIX_EPOCH;

use jikji_core::{JIKJI_DIR, JikjiError, PrepareOptions, Result, io_error};
use serde::Serialize;
use sha2::{Digest, Sha256};

const DEFAULT_IGNORE_PATTERNS: &[&str] = &["~$*", "Thumbs.db", ".DS_Store", "desktop.ini"];
const SENSITIVE_PATTERNS: &[&str] = &[
    ".git",
    ".hg",
    ".svn",
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    ".env",
    ".env.*",
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "*.pem",
    "*.key",
    "*.p12",
    "*.pfx",
];
const AGENT_RULES_BEGIN: &str = "<!-- BEGIN JIKJI ROUTING (auto-generated by `jikji prepare`; do not edit inside this block) -->";
const AGENT_RULES_END: &str = "<!-- END JIKJI ROUTING -->";
const AGENT_RULE_FILES: &[&str] = &["AGENTS.md", "CLAUDE.md", ".cursorrules"];

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ScanResult {
    pub root: PathBuf,
    pub files: Vec<PathBuf>,
    pub dirs: Vec<PathBuf>,
    pub truncated: bool,
    pub signature: SourceTreeSignature,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct SourceTreeSignature {
    pub algorithm: &'static str,
    pub digest: String,
    pub files: usize,
    pub folders: usize,
    pub total_size: u64,
    pub max_mtime_ns: u128,
}

pub fn scan_root(root: &Path, options: &PrepareOptions) -> Result<ScanResult> {
    let clean_root = root
        .canonicalize()
        .map_err(|source| io_error(root, source))?;
    if !clean_root.is_dir() {
        return Err(JikjiError::NotDirectory(clean_root));
    }

    let mut state = ScanState::new(options.clone());
    state.walk(&clean_root)?;
    state.files.sort();
    state.dirs.sort();
    let signature = source_tree_signature(&clean_root, &state.files, &state.dirs);

    Ok(ScanResult {
        root: clean_root,
        files: state.files,
        dirs: state.dirs,
        truncated: state.truncated,
        signature,
    })
}

struct ScanState {
    options: PrepareOptions,
    files: Vec<PathBuf>,
    dirs: Vec<PathBuf>,
    truncated: bool,
}

impl ScanState {
    fn new(options: PrepareOptions) -> Self {
        Self {
            options,
            files: Vec::new(),
            dirs: Vec::new(),
            truncated: false,
        }
    }

    fn walk(&mut self, current: &Path) -> Result<()> {
        if self.truncated {
            return Ok(());
        }
        let entries = match fs::read_dir(current) {
            Ok(entries) => entries,
            Err(error) if error.kind() == std::io::ErrorKind::PermissionDenied => return Ok(()),
            Err(source) => return Err(io_error(current, source)),
        };
        for entry in entries {
            if self.truncated {
                return Ok(());
            }
            let entry = match entry {
                Ok(entry) => entry,
                Err(error) if error.kind() == std::io::ErrorKind::PermissionDenied => continue,
                Err(source) => return Err(io_error(current, source)),
            };
            let name = entry.file_name().to_string_lossy().into_owned();
            if self.skip_name(&name) {
                continue;
            }
            let file_type = match entry.file_type() {
                Ok(file_type) => file_type,
                Err(_) => continue,
            };
            if file_type.is_symlink() {
                continue;
            }
            let path = entry.path();
            if file_type.is_dir() {
                self.dirs.push(path.clone());
                self.walk(&path)?;
                continue;
            }
            if file_type.is_file() {
                if is_pure_generated_agent_rule(&path, &name)? {
                    continue;
                }
                if self
                    .options
                    .max_files
                    .is_some_and(|limit| self.files.len() >= limit)
                {
                    self.truncated = true;
                    return Ok(());
                }
                self.files.push(path);
            }
        }
        Ok(())
    }

    fn skip_name(&self, name: &str) -> bool {
        name == JIKJI_DIR
            || self
                .options
                .exclude_patterns
                .iter()
                .any(|pattern| glob_match(pattern, name))
            || DEFAULT_IGNORE_PATTERNS
                .iter()
                .any(|pattern| glob_match(pattern, name))
            || (!self.options.include_hidden && name.starts_with('.'))
            || (!self.options.include_sensitive
                && SENSITIVE_PATTERNS
                    .iter()
                    .any(|pattern| glob_match(pattern, name)))
    }
}

fn is_pure_generated_agent_rule(path: &Path, name: &str) -> Result<bool> {
    if !AGENT_RULE_FILES.contains(&name) {
        return Ok(false);
    }
    let text = fs::read_to_string(path).map_err(|source| io_error(path, source))?;
    let trimmed = text.trim();
    Ok(trimmed.starts_with(AGENT_RULES_BEGIN) && trimmed.ends_with(AGENT_RULES_END))
}

fn source_tree_signature(root: &Path, files: &[PathBuf], dirs: &[PathBuf]) -> SourceTreeSignature {
    let mut hasher = Sha256::new();
    let mut file_count = 0usize;
    let mut total_size = 0u64;
    let mut max_mtime_ns = 0u128;

    for path in files {
        let metadata = match fs::metadata(path) {
            Ok(metadata) => metadata,
            Err(_) => continue,
        };
        let rel = rel_path(root, path);
        let size = metadata.len();
        let mtime_ns = metadata_mtime_ns(&metadata);
        file_count += 1;
        total_size = total_size.saturating_add(size);
        max_mtime_ns = max_mtime_ns.max(mtime_ns);
        hasher.update(rel.as_bytes());
        hasher.update(b"\0");
        hasher.update(size.to_string().as_bytes());
        hasher.update(b"\0");
        hasher.update(mtime_ns.to_string().as_bytes());
        hasher.update(b"\n");
    }

    SourceTreeSignature {
        algorithm: "sha256(relpath,size,mtime_ns).v1",
        digest: format!("{:x}", hasher.finalize()),
        files: file_count,
        folders: dirs.len() + 1,
        total_size,
        max_mtime_ns,
    }
}

pub(crate) fn rel_path(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .to_string_lossy()
        .replace(std::path::MAIN_SEPARATOR, "/")
}

pub(crate) fn metadata_mtime_ns(metadata: &fs::Metadata) -> u128 {
    metadata
        .modified()
        .ok()
        .and_then(|modified| modified.duration_since(UNIX_EPOCH).ok())
        .map_or(0, |duration| duration.as_nanos())
}

pub(crate) fn glob_match(pattern: &str, name: &str) -> bool {
    match (pattern.strip_prefix('*'), pattern.strip_suffix('*')) {
        (Some(suffix), _) => name.ends_with(suffix),
        (_, Some(prefix)) => name.starts_with(prefix),
        _ if pattern.contains('*') => {
            let mut parts = pattern.split('*');
            let prefix = parts.next().unwrap_or_default();
            let suffix = parts.next_back().unwrap_or_default();
            name.starts_with(prefix) && name.ends_with(suffix)
        }
        _ => pattern == name,
    }
}
